#
# CSE186 Assignment 8 Backend
#

openapi: '3.0.3'

info:
  description: CSE186 Assignment 8 Backend
  version: 0.1.0
  title: CSE186 Assignment 8 Backend

servers:
  - url: http://localhost:3010/v0

paths:
  /login:
    post:
      description: Login
      requestBody:
        description: Request Body
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Credentials'
      responses:
        200:
          description: Books Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /email:
    get:
      security:
        - bearerAuth: []
      description: returns all the main in a particular mailbox of a user
      parameters:
        - in: query
          name: mailbox
          required: false
          schema:
            type: string
      responses:
        200:
          description: EMail Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MailboxArray'
        404:
          description: Not Found
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /dummy:
    get:
      description: Dummy Endpoint
      responses:
        200:
          description: Succesful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DummyResponse'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Error:
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
      required:
        - code
        - message
    
    MailboxArray:
      type: array
      items:
        $ref: '#/components/schemas/Mailbox'
    Mailbox:
      type: object
      properties:
        name:
          type: string
        mail:
          type: array
          items:
            $ref: '#/components/schemas/MailboxEmail'
      required:
        - name
        - mail
    MailboxEmail:
      type: object
      properties:
        identifier:
          type: string
        emailid:
          type: string
        fromname:
          type: string
        toname:
          type: string
        content:
          type: object
          properties:
            message:
              type: string
        senttime:
          type: string
        receivedtime:
          type: string
        emailsubject:
          type: string
      required:
        - identifier
        - emailid
        - fromname
        - toname
        - content
        - senttime
        - receivedtime
        - emailsubject

    Credentials:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password

    User:
      type: object
      properties:
        name:
          type: string
        accessToken:
          type: string
      required:
        - name
        - accessToken

    DummyResponse:
      properties:
        message:
          type: string
      required:
        - message
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
